### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-api#215]
Update Readme with information from the qedc folder.

**Comment by vprusso** [comment]
Hmm. I wonder if we should keep the README file for the root `metriq-api` project relatively lean. As the `benchmark/` component is fairly separate and also has its own self-contained README file ([here](https://github.com/unitaryfund/metriq-api/blob/main/benchmark/README.md)). 

I would opt to keep the separation, but I'm open to opposition. Thoughts @WrathfulSpatula , @nathanshammah ?

**Comment by WrathfulSpatula** [comment]
I think your stance on this makes sense, @vprusso. I don't know if @nathanshammah has more to say, but I would defer to you.

**Comment by WrathfulSpatula** [comment]
Maybe we could link the secondary README in the main README?

**Comment by vprusso** [comment]
Addressed in https://github.com/unitaryfund/metriq-api/pull/217
